### ISSUE TITLE
Forest Admin throws error on login 

### ISSUE THREAD

**Issue by malavikavarma** [ForestAdmin/forest-express-sequelize#218]
## Expected behavior

On login to forest admin ,it should render the graphs and all other details of the models should be rendered. 

## Actual behavior

Currently , forest admin throws error in UI as follows: 
**Oops, something went wrong.An error occurred in retrieving your data.** On logging out and logging in back there is no occurrence of the error. And backend throws error: **invalid byte sequence for encoding utf8**

There is a token being set during the time of login **forest_session_token** . This token is being generated by forest admin server. On relogin this token changes and the data is fetched correctly without error. This error occurs repeatedly.

Database used: Postgres

I need to know why this error occurs?

**Comment by arnaudbesnier** [comment]
Hi @malavikavarma,

Thanks for the feedback.

- Could you share the full error logs (if any) you have in your backend?
- Also do you know how long does it takes for a new "working" session to generate a buggy behaviour?
- Another idea, do you use some browser plugins that could corrupt the session token during its lifetime? In other words, do you observe the same behaviour in an "Incognito" mode/window (without plugins)?

**Comment by malavikavarma** [comment]
- This is  the error message that I got in my backend -
 `"err":{"message":"invalid byte sequence for encoding \"UTF8\": 0x00","name":"error","stack":"error: invalid byte sequence for encoding \"UTF8\": 0x00\n    at Connection.parseE (/home/app/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/home/app/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/home/app/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","code":"22021"},"msg":"{ path: '/forest/forest/accounts/count',\n  query:\n   { fields:\n      { accounts:\n         'id,email,status,first_name,last_name,created_at,emailverified,billing_start_date,affiliate_link' },\n     searchExtended: '0',\n     timezone: 'Asia/Calcutta' },\n  body: undefined }","time":"2019-02-23T01:08:54.345Z","v":0}
`

- On first login I get this error and after signing out and signing in back soon there is no error.

- I have not added any extensions. I have tried using different browsers. Still I got the error.

**Comment by arnaudbesnier** [comment]
Hi @malavikavarma, do you think it could be related to this kind of discussions:
- https://stackoverflow.com/questions/4867272/invalid-byte-sequence-for-encoding-utf8
- https://dba.stackexchange.com/questions/4777/how-to-solve-utf8-invalid-byte-sequence-copy-errors-on-a-restore-when-the-sourc

I am not really sure this is related to Forest.
