### ISSUE TITLE
Sequelize - Support Sequelize 6 (model.build error on new insertion)

### ISSUE THREAD

**Issue by laruche** [ForestAdmin/forest-express-sequelize#312]
Found an error with sequelize 6.0.0 dependencies 

`[forest] 🌳🌳🌳  Unexpected error: model.build is not a function
TypeError: model.build is not a function
    at ResourceCreator.perform (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express-sequelize/dist/services/resource-creator.js:20:31)
    at /home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/dist/routes/resources.js:58:64
    at tryCatcher (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:629:18)
    at PromiseArray._resolve (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise_array.js:143:14)
    at PromiseArray._iterate (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise_array.js:113:31)
    at PromiseArray.init [as _init] (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:557:21)
    at Promise._settlePromise0 (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:629:18)
    at PromiseArray._resolve (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:565:26)
    at Promise._settlePromise0 (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues (/home/laruche/Sites/Cadi+/API/cadiplus_sql/node_modules/forest-express/node_modules/bluebird/js/release/async.js:16:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
` 

revert to 5.19 version and this is ok

**Comment by mettiu** [comment]
Hi. 
I just tried with sequelize 6.17.0 (forest-express sequelize version 7.9.3) and I had no problems.

Is this an outdated issue?
Is sequelize 6.x definitely supported by Forest?

Thank you

**Comment by jeffladiray** [comment]
It is indeed an outdated issue.
I can confirm that we should be compatible with `sequelize@6.0`, so I'll close this issue 👍 

(As a side note, we tend to answer much faster on our [discourse community](https://community.forestadmin.com), so don't hesitate to reach out to us there!)
